### ISSUE TITLE
help, bro.

### ISSUE THREAD

**Issue by WangNingkai** [AlphaNecron/Hackintosh-EFI-H510M-K#2]
cpu：i7-10700
board: H510M-k
![image](https://github.com/AlphaNecron/Hackintosh-EFI-H510M-K/assets/23030927/d5343950-ce31-47ad-8e99-b263c757e6cf)
![image](https://github.com/AlphaNecron/Hackintosh-EFI-H510M-K/assets/23030927/28cf4a49-19ea-4073-b8b3-b6ba6435b294)

i have no gpu，how can i make efi to install hackintosh.thanks.

**Comment by AlphaNecron** [comment]
H510M-K does not support iGPU.
